import type { Metadata } from "next";
import { Barlow_Condensed, Bellefair } from "next/font/google";
import "./globals.css";

const barlow = Barlow_Condensed({
  variable: "--font-barlow",
  weight: "400",
});

const bellefair = Bellefair({
  variable: "--font-bellefair",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Space Turismo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${barlow.variable} ${bellefair.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
